services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: DockerfileQueryBot
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db/dbname
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data: